# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51fe9cdee8d16b79fcbd9e70b467d30d99c31eb1c32a43e7c7da8dfaa2a2626243bc2bb7c0ec3c6a8cc880525fda6ca0d3eeb652c9cb90923dd91b9a42e9f106

test:
  secret_key_base: c3fe008a8e34c5aae7d2c86d03971f080c8c2631fcc8a8e0477aa50983db7d2e0272d53a8fc469081b8551b1f16017c5d3efc460c7320c650e959cd23516e35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
